### PR TITLE
Error message after the stack trace

### LINKED ISSUE #62: Post error message after stacktrace
When an exception is thrown with the exception macro and caught by the framework, we first output the error message and then a stacktrace. Most of the time, the user is more interested in the error message than the stacktrace so ideally it should be the first thing they see. Currently, it is often hidden behind a stack trace which at least has 6 or 7 frames in it. This is especially important for beginners. 

Since there have been issues with the stacktrace code crashing, it will still be useful to have the error message printed before the stack trace as well. I think we can afford that overhead.

### PR DESCRIPTION
**Pull request by EinarElen**
This resolves https://github.com/LDMX-Software/Framework/issues/62

### CODE REVIEW

File: src/Framework/fire.cxx [hunk 1]
```diff
@@ -79,11 +79,18 @@ int main(int argc, char* argv[]) {
                                    argc - ptrpy - 1);
     p = cfg.makeProcess();
   } catch (framework::exception::Exception& e) {
+    // Error message currently printed twice since the stack trace code
+    // sometimes crashes. Once this is fixed, the output above the stack trace
+    // can be removerd.
```
Comment (tomeichlersmith) [inline src/Framework/fire.cxx]: Just adding link to the issue that is related to this comment.
```suggestion
    // can be removed
    // https://github.com/LDMX-Software/Framework/issues/50
```

**Review by tomeichlersmith — COMMENTED** [review]
Looks good :+1:

Just adding a reference to the issue related to the stack-trace seg faulting https://github.com/LDMX-Software/Framework/issues/50
